# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radar_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1020)
        self.main_demo = QtWidgets.QLabel(MainWindow)
        self.main_demo.setGeometry(QtCore.QRect(330, 10, 1030, 688))
        self.main_demo.setMinimumSize(QtCore.QSize(772, 516))
        self.main_demo.setMaximumSize(QtCore.QSize(1030, 688))
        self.main_demo.setObjectName("main_demo")
        self.message_box = QtWidgets.QLabel(MainWindow)
        self.message_box.setGeometry(QtCore.QRect(10, 710, 640, 301))
        self.message_box.setMinimumSize(QtCore.QSize(640, 280))
        self.message_box.setMaximumSize(QtCore.QSize(480, 16777215))
        self.message_box.setObjectName("message_box")
        self.base_img = QtWidgets.QLabel(MainWindow)
        self.base_img.setGeometry(QtCore.QRect(660, 710, 700, 300))
        self.base_img.setMinimumSize(QtCore.QSize(400, 300))
        self.base_img.setMaximumSize(QtCore.QSize(700, 300))
        self.base_img.setObjectName("base_img")
        self.Tips = QtWidgets.QLabel(MainWindow)
        self.Tips.setGeometry(QtCore.QRect(1370, 880, 160, 131))
        self.Tips.setMinimumSize(QtCore.QSize(160, 0))
        self.Tips.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Tips.setObjectName("Tips")
        self.feedback = QtWidgets.QLabel(MainWindow)
        self.feedback.setGeometry(QtCore.QRect(1547, 880, 351, 131))
        self.feedback.setMinimumSize(QtCore.QSize(300, 120))
        self.feedback.setMaximumSize(QtCore.QSize(360, 160))
        self.feedback.setObjectName("feedback")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setGeometry(QtCore.QRect(12, 12, 310, 673))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.map = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setMinimumSize(QtCore.QSize(308, 575))
        self.map.setMaximumSize(QtCore.QSize(308, 575))
        self.map.setObjectName("map")
        self.verticalLayout.addWidget(self.map)
        self.btn1 = QtWidgets.QPushButton(self.widget)
        self.btn1.setMinimumSize(QtCore.QSize(240, 25))
        self.btn1.setMaximumSize(QtCore.QSize(308, 25))
        self.btn1.setObjectName("btn1")
        self.verticalLayout.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.widget)
        self.btn2.setMinimumSize(QtCore.QSize(240, 25))
        self.btn2.setMaximumSize(QtCore.QSize(308, 25))
        self.btn2.setObjectName("btn2")
        self.verticalLayout.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.widget)
        self.btn3.setObjectName("btn3")
        self.verticalLayout.addWidget(self.btn3)
        self.widget1 = QtWidgets.QWidget(MainWindow)
        self.widget1.setGeometry(QtCore.QRect(1370, 10, 532, 856))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.second_cam = QtWidgets.QLabel(self.widget1)
        self.second_cam.setMinimumSize(QtCore.QSize(530, 424))
        self.second_cam.setMaximumSize(QtCore.QSize(530, 424))
        self.second_cam.setObjectName("second_cam")
        self.verticalLayout_2.addWidget(self.second_cam)
        self.third_cam = QtWidgets.QLabel(self.widget1)
        self.third_cam.setMinimumSize(QtCore.QSize(530, 424))
        self.third_cam.setMaximumSize(QtCore.QSize(530, 424))
        self.third_cam.setObjectName("third_cam")
        self.verticalLayout_2.addWidget(self.third_cam)

        self.retranslateUi(MainWindow)
        self.btn1.clicked.connect(MainWindow.btn1_clicked)
        self.btn2.clicked.connect(MainWindow.btn2_clicked)
        self.btn3.clicked.connect(MainWindow.btn3_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Radarstation2024_two_layers_three_cam"))
        self.main_demo.setText(_translate("MainWindow", "main_demo"))
        self.message_box.setText(_translate("MainWindow", "message_box"))
        self.base_img.setText(_translate("MainWindow", "base_img"))
        self.Tips.setText(_translate("MainWindow", "<html><head/><body><p>Aerial</p><p>R record ; D stop</p><p>C change view</p></body></html>"))
        self.feedback.setText(_translate("MainWindow", "feedback"))
        self.map.setText(_translate("MainWindow", "map"))
        self.btn1.setText(_translate("MainWindow", "btn1"))
        self.btn2.setText(_translate("MainWindow", "btn2"))
        self.btn3.setText(_translate("MainWindow", "btn3"))
        self.second_cam.setText(_translate("MainWindow", "second_cam"))
        self.third_cam.setText(_translate("MainWindow", "third_cam"))

